# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0002_auto_20160921_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
    ]
