# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0003_remove_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 21, 23, 24, 48, 145109)),
        ),
    ]
