# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0006_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.CharField(default='00:00', max_length=50),
        ),
    ]
