# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0010_auto_20160922_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
